# SPDX-FileCopyrightText: 2026 Leonardo Muffato (AUTOSOFT Engineering - www.autosoft-engineering.de)
# SPDX-License-Identifier: MIT

"""Canonical public schema surface for AI Software Architect."""

from .models import (
    ArchitectureAnalysisResult,
    ArchitectureContract,
    ArchitectureDecision,
    ArchitectureDecisionArtifact,
    ArchitectureOption,
    ArtifactSecretScanInput,
    ArtifactSecretScanResult,
    BoundaryCheckInput,
    ClarificationQuestion,
    Component,
    ConformanceFinding,
    ConformanceReport,
    ContractValidationInput,
    ContractValidationResult,
    DecisionListInput,
    DecisionListResult,
    DependencyEdge,
    DependencyGraphEvidence,
    DependencyRule,
    ExternalBoundary,
    QualityAttribute,
    RepositoryAnalysisInput,
    SecretFinding,
    StrictModel,
    StrikeEvent,
    ToolError,
    WorkflowNode,
    WorkflowState,
    WorkflowStatus,
)

__all__ = [
    "ArchitectureAnalysisResult",
    "ArchitectureContract",
    "ArchitectureDecision",
    "ArchitectureDecisionArtifact",
    "ArchitectureOption",
    "ArtifactSecretScanInput",
    "ArtifactSecretScanResult",
    "BoundaryCheckInput",
    "ClarificationQuestion",
    "Component",
    "ConformanceFinding",
    "ConformanceReport",
    "ContractValidationInput",
    "ContractValidationResult",
    "DecisionListInput",
    "DecisionListResult",
    "DependencyEdge",
    "DependencyGraphEvidence",
    "DependencyRule",
    "ExternalBoundary",
    "QualityAttribute",
    "RepositoryAnalysisInput",
    "SecretFinding",
    "StrictModel",
    "StrikeEvent",
    "ToolError",
    "WorkflowNode",
    "WorkflowState",
    "WorkflowStatus",
]

